### ISSUE TITLE
Premium BP calculation (15 levels)

### ISSUE THREAD

**Issue by Saarien** [Gardnem6/wt-passhelper#1]
**Current Behavior**
'Is It Possible To Get the Level 75 Reward' does not take into consideration if user input 'Current Battlepass Level' already includes 15 levels from BP , making output incorrect.

**Steps to Reproduce**
1. Input Current Battlepass Level: 57
2. Your Possible Level With Logins, Easy Tasks, and Medium Tasks will show: 60.6
3. 'Is It Possible To Get the Level 75 Reward' will be 'yes'
This is incorrect in case of user having already bought 15 levels premium BP (it will be level 60.6 with those premium levels , not added after to reach 75)

**Possible Solution**
a: Show 2 answers 'Yes' or 'No' for having bought 15 levels premium or not.
b: Add a tick for having  bought 15 levels premium (thus already including them into user input of 'Current BP level'

**Comment by Gardnem6** [comment]
Thank you for reporting this. I've got some updates planned for this battlepass season so I'll work on something to make this better.
