### ISSUE TITLE
New Battlepass "Airborne General"

### ISSUE THREAD

**Issue by dev-nul1** [Gardnem6/wt-passhelper#7]

**Comment by LaurentDumont** [comment]
I just had a go at this (shamelessly stealing the current repo) - I just wanted to learn a bit more about Vu frontend stuff

https://laurentdumont.github.io/wt-passhelper/

**Comment by Gardnem6** [comment]
I fixed this a month ago on the wrong branch. I am an idiot. Everything should be good now!
